name = "sdg-cat"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SdgCat"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/joelriou/mathlib4.git"
rev = "ring-object"

[[lean_lib]]
name = "SdgCat"
